In [0]:
import numpy as np


### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np


arr = np.random.randint(1, 51, size=10)


mean_value = np.mean(arr)
std_value = np.std(arr)

print("Array: ", arr)
print("Média: ", mean_value)
print("Desvio padrão: ", std_value)

Média:  26.9  Desvio:  8.722958213817146


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)

#calcular a raiz quadrada dos valores menores ou iguais a 0,5
array[array <= 0.5] = np.sqrt(array[array <= 0.5])

print(array)

[0.81892976 0.45413819 0.11250773 0.59531782 0.94575634 0.56484621
 0.82182093 0.39044712 0.98639856 0.61153414]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)
max_linhas = np.amax(matriz, axis=1)

print(max_linhas)
print(matriz)

[[0.79280883 0.58920088 0.84781977]
 [0.87678247 0.6309046  0.7774392 ]
 [0.42942495 0.97347431 0.55207012]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)

media = np.mean(matriz, axis=1)
matriz_sub = matriz - media[:, np.newaxis]
print(matriz_sub)

[[ 0.00849187 -0.19305067  0.54295817 -0.15623827 -0.2021611 ]
 [-0.33654681  0.07293933  0.01178802 -0.04217057  0.29399003]
 [-0.38935783 -0.00683046 -0.06880354  0.22162458  0.24336725]
 [ 0.20360664 -0.33002746 -0.39621562  0.2562984   0.26633803]
 [ 0.20363586  0.11502338 -0.51786392  0.23149626 -0.03229158]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
import numpy as np

# Criar uma matriz de tamanho 4x4 com valores aleatórios
matriz = np.random.rand(4, 4)

# Calcular a média e o desvio padrão das diagonais da matriz
diag_principal = np.diag(matriz)
diag_secundaria = np.diag(np.fliplr(matriz))
media_diag = np.mean([diag_principal, diag_secundaria])
std_diag = np.std([diag_principal, diag_secundaria])

print("Matriz:\n", matriz)
print("Diagonal principal:\n", diag_principal)
print("Diagonal secundária:\n", diag_secundaria)
print("Média das diagonais:", media_diag)
print("Desvio padrão das diagonais:", std_diag)


Matriz:
 [[0.48360437 0.44989675 0.12258417 0.98119165]
 [0.63027433 0.65568235 0.61543591 0.85524746]
 [0.48152219 0.82169169 0.10067373 0.06259742]
 [0.47159853 0.38195253 0.72873707 0.70023361]]
Média da diagonal principal: 0.4850485156662547
Desvio padrão da diagonal principal: 0.2362025551237588
Média da diagonal secundária: 0.7224794428836074
Desvio padrão da diagonal secundária: 0.19440590680767922
